# Generated by Django 4.0.3 on 2022-03-06 10:29

import django.core.validators
from django.db import migrations, models
import validators.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), validators.custom_validators.validator_only_letters_numbers])),
                ('category', models.TextField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Puzzle', 'Puzzle'), ('Simulation', 'Simulation'), ('Strategy', 'Strategy'), ('Sports', 'Sports'), ('Others', 'Others')], max_length=10)),
                ('max_level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(upload_to='game_images', validators=[validators.custom_validators.ValidatorMaxSizeInMB(10)])),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
