# Generated by Django 4.0.3 on 2022-03-08 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
